/*
 * roboshell.h
 *
 *  Created on: Feb 12, 2013
 *      Author: armin
 */

#ifndef ROBOSHELL_H_
#define ROBOSHELL_H_

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <portmacro.h>

#include "tokens.h"


/********** DEFINITIONS **********************/

#define EOL -666
#define ERR -777


/********** TYPE DEFINITIONS **********************/

typedef struct Scanner {
    char *curpos;
    unsigned int line;
} CLI_Scanner_t;


typedef struct Token {
    char *s;
    int n;
    int id;
} CLI_Token_t;

typedef int (*CLI_Command_Callback_t)(int, char**);


typedef struct command_callback_def
{
	const char* const command_str;		/* The command that causes pxCommandInterpreter to be executed.  For example "help".  Must be all lower case. */
	const char* const help_str;			/* String that describes how to use the command.  Should start with the command itself, and end with "\r\n".  For example "help: Returns a list of all the commands\r\n". */
	CLI_Command_Callback_t command_func;		/* A pointer to the callback function that will return the output generated by the command. */
	unsigned int parameter_count;		/* Commands expect a fixed number of parameters, which may be zero. */
} CLI_Command_Callback_Definition_t;


typedef struct command_callback_list_item
{
	CLI_Command_Callback_Definition_t *command;
	struct command_callback_list_item *next;
} CLI_Command_Callback_List_Item_t;


/********** FUNCTION PROTOTYPES **********************/


unsigned int scan(CLI_Scanner_t *s, CLI_Token_t *t);


#endif /* ROBOSHELL_H_ */
